/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_v1_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Photo */
        post: operations["register_photo_v1_sessions__session_id__photos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_v1_sessions__session_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_v1_sessions__session_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Result */
        get: operations["result_v1_sessions__session_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review */
        get: operations["review_v1_sessions__session_id__review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/sessions/{session_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace */
        get: operations["get_trace_v1_admin_sessions__session_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisResult */
        AnalysisResult: {
            /** Session Id */
            session_id: string;
            /** Top 2 Seasons */
            top_2_seasons: [
                "Spring" | "Summer" | "Autumn" | "Winter",
                "Spring" | "Summer" | "Autumn" | "Winter"
            ];
            scorecard: components["schemas"]["Scorecard"];
            reliability: components["schemas"]["Reliability"];
            /**
             * Result State
             * @enum {string}
             */
            result_state: "ok" | "ok_low_reliability" | "insufficient_photos" | "no_face_detected" | "multiple_subjects" | "filter_suspected" | "failed";
            /** Trace */
            trace: string[];
            /** Color Swatches */
            color_swatches?: {
                [key: string]: string;
            } | null;
            measurement_explanation?: components["schemas"]["MeasurementExplanation"] | null;
        };
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /**
             * Force Recompute
             * @default false
             */
            force_recompute: boolean;
        };
        /** AnalyzeResponse */
        AnalyzeResponse: {
            /** Accepted */
            accepted: boolean;
        };
        /** AxisExplanation */
        AxisExplanation: {
            /**
             * Key
             * @enum {string}
             */
            key: "warmth" | "value" | "chroma" | "contrast";
            /** Label */
            label: string;
            /** Summary */
            summary: string;
        };
        /** MeasurementDetail */
        MeasurementDetail: {
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** MeasurementExplanation */
        MeasurementExplanation: {
            /** Note */
            note: string;
            /** Photos */
            photos: components["schemas"]["MeasurementPhoto"][];
            /** Readings */
            readings: components["schemas"]["MeasurementReading"][];
            /** Axis Explanations */
            axis_explanations: components["schemas"]["AxisExplanation"][];
        };
        /** MeasurementOverlay */
        MeasurementOverlay: {
            /**
             * Id
             * @enum {string}
             */
            id: "skin" | "hair" | "left_eye" | "right_eye";
            /**
             * Group
             * @enum {string}
             */
            group: "skin" | "hair" | "eyes";
            /** Label */
            label: string;
            /** Anchor X */
            anchor_x: number;
            /** Anchor Y */
            anchor_y: number;
            /** Polygons */
            polygons: components["schemas"]["MeasurementPoint"][][];
        };
        /** MeasurementPhoto */
        MeasurementPhoto: {
            /** Photo Id */
            photo_id: string;
            /** Filename */
            filename: string;
            /** Preview Url */
            preview_url: string;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
            /** Overlays */
            overlays: components["schemas"]["MeasurementOverlay"][];
        };
        /** MeasurementPoint */
        MeasurementPoint: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** MeasurementReading */
        MeasurementReading: {
            /**
             * Key
             * @enum {string}
             */
            key: "skin" | "hair" | "eyes";
            /** Label */
            label: string;
            /** Summary */
            summary: string;
            /** Swatch */
            swatch?: string | null;
            /** Technical Details */
            technical_details?: components["schemas"]["MeasurementDetail"][];
        };
        /** PhotoRegisterRequest */
        PhotoRegisterRequest: {
            /** Filename */
            filename: string;
            /** Mime Type */
            mime_type: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** PhotoRegisterResponse */
        PhotoRegisterResponse: {
            /** Id */
            id: string;
            /** Accepted */
            accepted: boolean;
            /** Reasons */
            reasons: ("session_not_pending" | "photo_limit_exceeded" | "invalid_filename" | "unsupported_mime_type")[];
            /** Upload Url */
            upload_url?: string | null;
            /** Upload Fields */
            upload_fields?: {
                [key: string]: string;
            } | null;
        };
        /** ProblemDetail */
        ProblemDetail: {
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /** Detail */
            detail: string;
            /**
             * Error Code
             * @enum {string}
             */
            error_code: "invalid_session" | "session_not_found" | "session_deleted" | "insufficient_photos" | "already_running" | "already_complete" | "result_not_ready" | "forbidden" | "invalid_request" | "internal_error" | "rate_limit_exceeded";
        };
        /** RejectedPhotoReview */
        RejectedPhotoReview: {
            /** Photo Id */
            photo_id: string;
            /** Filename */
            filename: string;
            /** Reasons */
            reasons: ("blurry" | "bad_exposure" | "no_face_detected" | "multiple_subjects" | "decode_failed")[];
            /** Preview Url */
            preview_url: string;
        };
        /** RejectionSummaryItem */
        RejectionSummaryItem: {
            /**
             * Code
             * @enum {string}
             */
            code: "blurry" | "bad_exposure" | "no_face_detected" | "multiple_subjects" | "decode_failed";
            /** Count */
            count: number;
        };
        /** Reliability */
        Reliability: {
            /** Score */
            score: number;
            /**
             * Bucket
             * @enum {string}
             */
            bucket: "High" | "Medium" | "Low";
            /** Reasons */
            reasons: string[];
        };
        /** Scorecard */
        Scorecard: {
            /** Warmth */
            warmth: number;
            /** Value */
            value: number;
            /** Chroma */
            chroma: number;
            /** Contrast */
            contrast: number;
        };
        /** SessionCreateResponse */
        SessionCreateResponse: {
            /** Id */
            id: string;
            /** Status */
            status: string;
        };
        /** SessionReviewResponse */
        SessionReviewResponse: {
            /** Rejected Photos */
            rejected_photos: components["schemas"]["RejectedPhotoReview"][];
        };
        /** StatusResponse */
        StatusResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "complete" | "failed" | "deleted";
            /** Result State */
            result_state?: ("ok" | "ok_low_reliability" | "insufficient_photos" | "no_face_detected" | "multiple_subjects" | "filter_suspected" | "failed") | null;
            /** Rejection Summary */
            rejection_summary?: components["schemas"]["RejectionSummaryItem"][] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_session_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCreateResponse"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    delete_session_v1_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error response with stable error_code for client handling. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    register_photo_v1_sessions__session_id__photos_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhotoRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoRegisterResponse"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    analyze_v1_sessions__session_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    status_v1_sessions__session_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    result_v1_sessions__session_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    review_v1_sessions__session_id__review_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionReviewResponse"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_trace_v1_admin_sessions__session_id__trace_get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error response with stable error_code for client handling. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Error response with stable error_code for client handling. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
