FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

COPY pyproject.toml /app/pyproject.toml
RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir .

COPY src /app/src
COPY alembic.ini /app/alembic.ini
COPY alembic /app/alembic

CMD ["python", "-m", "color_analysis.workers.main"]
